from django.db import models
from django.conf import settings

class Jos_session(models.Model):
	"""Model representating session in joomla DB.
	Autogenerated from database with command: python manage.py inspectdb
	"""
	username = models.CharField(max_length=450, blank=True)
	time = models.CharField(max_length=42, blank=True)
	session_id = models.CharField(max_length=600, primary_key=True)
	guest = models.IntegerField(null=True, blank=True)
	userid = models.IntegerField(null=True, blank=True)
	usertype = models.CharField(max_length=150, blank=True)
	gid = models.IntegerField()
	client_id = models.IntegerField()
	data = models.TextField(blank=True)

	class Meta:
		db_table = u'jos_session'
		verbose_name = u'session'
	
	def __unicode__(self):
		return "%s" % self.session_id

	def save(self, *args, **kwargs):
		pass

class Jos_joom_gallery_catg(models.Model):
	"""Category of gallery.
	Autogenerated from database with command: python manage.py inspectdb
	"""
	cid = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=765)
	parent = models.IntegerField()
	description = models.TextField(blank=True)
	ordering = models.IntegerField()
	access = models.IntegerField()
	published = models.CharField(max_length=3)
	owner = models.IntegerField(null=True, blank=True)
	catimage = models.CharField(max_length=300, blank=True)
	img_position = models.IntegerField(null=True, blank=True)
	catpath = models.CharField(max_length=765)

	class Meta:
		db_table = u'jos_joomgallery_catg'
		verbose_name = u'category of gallery'
		verbose_name_plural = u'categories of gallery'

	def __unicode__(self):
		return "%s" % (self.name)

	def save(self, *args, **kwargs):
		pass

class Jos_joom_gallery(models.Model):
	"""Model representating gallery in joomla DB.
	Autogenerated from database with command: python manage.py inspectdb
	"""
	id = models.IntegerField(primary_key=True)
	catid = models.ForeignKey(Jos_joom_gallery_catg, db_column='catid')
	imgtitle = models.TextField()
	imgauthor = models.CharField(max_length=150, blank=True)
	imgtext = models.TextField()
	imgdate = models.CharField(max_length=60, blank=True)
	imgcounter = models.IntegerField()
	imgvotes = models.IntegerField()
	imgvotesum = models.IntegerField()
	published = models.IntegerField()
	imgfilename = models.CharField(max_length=300)
	imgthumbname = models.CharField(max_length=300)
	checked_out = models.IntegerField()
	owner = models.IntegerField()
	approved = models.IntegerField()
	useruploaded = models.IntegerField()
	ordering = models.IntegerField()

	class Meta:
		db_table = u'jos_joomgallery'
		verbose_name = u'gallery'
		verbose_name_plural = u'galleries'
	
	def __unicode__(self):
		return "(%s) %s" % (self.id, self.imgtitle)

	def get_thumb_url(self):
		return "%scomponents/com_joomgallery/img_thumbnails/%s/%s" % (settings.SNP_JOOMLA_URL,
			self.catid.catpath, self.imgthumbname)

	def get_photo_url(self):
		return "%scomponents/com_joomgallery/img_pictures/%s/%s" % (settings.SNP_JOOMLA_URL,
			self.catid.catpath, self.imgthumbname)

	def save(self, *args, **kwargs):
		pass

class Jos_content(models.Model):
	"""Model representating gallery in joomla DB.
	Autogenerated from database with command: python manage.py inspectdb
	"""
	id = models.IntegerField(primary_key=True)
	title = models.CharField(max_length=765)
	alias = models.CharField(max_length=765)
	title_alias = models.CharField(max_length=765)
	introtext = models.TextField()
	fulltext = models.TextField()
	state = models.IntegerField()
	sectionid = models.IntegerField()
	mask = models.IntegerField()
	catid = models.IntegerField()
	created = models.DateTimeField()
	created_by = models.IntegerField()
	created_by_alias = models.CharField(max_length=765)
	modified = models.DateTimeField()
	modified_by = models.IntegerField()
	checked_out = models.IntegerField()
	checked_out_time = models.DateTimeField()
	publish_up = models.DateTimeField()
	publish_down = models.DateTimeField()
	images = models.TextField()
	urls = models.TextField()
	attribs = models.TextField()
	version = models.IntegerField()
	parentid = models.IntegerField()
	ordering = models.IntegerField()
	metakey = models.TextField()
	metadesc = models.TextField()
	access = models.IntegerField()
	hits = models.IntegerField()
	metadata = models.TextField()

	class Meta:
		db_table = u'jos_content'
		verbose_name = u'content'

	def __unicode__(self):
		return "(%s) %s" % (self.id, self.title)

	def get_article_url(self):
		return '%sindex.php?option=com_content&id=%s' % (settings.SNP_JOOMLA_URL, self.id)

	def save(self, *args, **kwargs):
		pass

class JosUsers(models.Model):
	id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=150)
	username = models.CharField(max_length=75)
	email = models.CharField(max_length=300)
	password = models.CharField(max_length=300)
	usertype = models.CharField(max_length=75)
	block = models.IntegerField()
	sendemail = models.IntegerField(null=True, db_column='sendEmail', blank=True) # Field name made lowercase.
	gid = models.IntegerField()
	registerdate = models.DateTimeField(db_column='registerDate') # Field name made lowercase.
	lastvisitdate = models.DateTimeField(db_column='lastvisitDate') # Field name made lowercase.
	activation = models.CharField(max_length=300)
	params = models.TextField()

	def __unicode__(self):
		return "%s" % self.username

	def save(self, *args, **kwargs):
		pass

	class Meta:
		db_table = u'jos_users'
		verbose_name = u'user'
		verbose_name_plural = u'users'
